name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 0 点（北京时间 8 点）
  workflow_dispatch: # 手动触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          upstream_sync_repo: wxxsfxyzm/InstallerX-Revived
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for errors
        if: failure()
        run: |
          echo "[Error] 由于上游冲突或其他原因，同步失败。"
          exit 1
